Neos:
  Flow:
    http:
      middlewares:
        'graphQLOptions':
          position: 'before routing'
#          position: 'before requestUriHostParameter'
          middleware: 'Wwwision\GraphQL\Middleware\HttpOptionsMiddleware'

Wwwision:
  GraphQL:
    endpoints: []
#      'some-endpoint':
#        'queryType': 'Some\Fully\Qualified\Namespace'
#        'mutationType': 'Some\Fully\Qualified\Namespace'
